---
title: "EDA： numeric summaries"
author: "Ruoxi Li"
date: "`r Sys.Date()`"
output: github_document
---

month = lubridate::floor_date(date, unit = "month")
count(name, name= "n_obs")
group_by(name,month) |>
summarize(n_obs = n())
 pivot_wider(
    names_from = name,
    values_from = n
  )
```{r}
library(tidyverse)
library(ggplot2)
```

## data import

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2023-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) |>
  select(name, id, everything())
```

## Initial numeric work

```{r}
weather_df |>
  ggplot(aes(x=prcp)) +
  geom_histogram()
```

here are the big outliers
```{r}
weather_df |>
  filter(prcp>1000)
```

```{r}
weather_df |>
  filter(tmax>=20, tmax<30)|>
  ggplot(aes(x = tmin, y=tmax, color=name))+
  geom_point()
```

## Grouping

```{r}
weather_df |>
  group_by(name,month)
```

## Counting

```{r}
weather_df |>
  group_by(name,month)|>
  summarize(n_obs = n())


weather_df |>
  group_by(month)|>
  summarize(n_obs = n())
```

```{r}
weather_df |>
  count(name, name= "n_obs")
```

```{r}
weather_df |>
  count(name, month) |>
  pivot_wider(
    names_from = name,
    values_from = n
  )
```

## General summaries

```{r}
weather_df |>
  #drop_na(tmax)|>
  group_by(name,month) |>
  summarize(
    mean_tmax = mean(tmax,na.rm = TRUE),
    median_tmax = median(tmax, na.rm = TRUE),
    sd_tmax = sd(tmax,na.rm = TRUE)
    #na.rm = true 意思是舍弃所有na
  )
```

```{r}
weather_df |>
  group_by(name,month) |>
  summarize( mean_tmax = mean(tmax,na.rm = TRUE))|>
  ggplot(aes(x = month, y=mean_tmax, color=name))+
  geom_point()+
  geom_line()
```

```{r}
weather_df |>
  group_by(name,month) |>
  summarize( mean_tmax = mean(tmax,na.rm = TRUE))|>
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  )|>
  knitr::kable(digits = 2)
```


```{r}
